name: json_model_builder
description: A sample command-line application.
version: 0.2.0
homepage: https://github.com/Martoxdlol/dart_json_model_builder

environment:
  sdk: '>=2.18.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  json_diff: ^0.2.1
