name: json_model_builder
description: Create model as classes that can be serialized from/to JSON. It supports different types custom models, and more. It doesn't use code generation or mirrors 
version: 0.2.0
homepage: https://github.com/Martoxdlol/dart_json_model_builder
repository: https://github.com/Martoxdlol/dart_json_model_builder
documentation: https://github.com/Martoxdlol/dart_json_model_builder/blob/master/README.md

platforms:
  - android
  - ios
  - linux
  - macos
  - web
  - windows

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  json_diff: ^0.2.1
